import type { Deck } from "./types";

export const decks: Deck[] = [
  {
    id: "deck-math-aa",
    subjectSlug: "math-aa",
    title: "Math AA HL key formulas & terms",
    cards: [
      { id: "maac-1", front: "Arithmetic nth term", back: "uₙ = u₁ + (n−1)d" },
      { id: "maac-2", front: "Arithmetic series", back: "Sₙ = n/2(2u₁ + (n−1)d)" },
      { id: "maac-3", front: "Geometric nth term", back: "uₙ = u₁·rⁿ⁻¹" },
      { id: "maac-4", front: "Geometric series (finite)", back: "Sₙ = u₁(rⁿ−1)/(r−1)" },
      { id: "maac-5", front: "Geometric series (∞)", back: "S∞ = u₁/(1−r), |r| < 1" },
      { id: "maac-6", front: "Change of base", back: "logₐb = ln b / ln a" },
      { id: "maac-7", front: "log laws: product", back: "log(xy) = log x + log y" },
      { id: "maac-8", front: "Quadratic formula", back: "x = (−b ± √(b²−4ac)) / 2a" },
      { id: "maac-9", front: "Discriminant", back: "Δ = b²−4ac; >0 two roots, =0 one, <0 none" },
      { id: "maac-10", front: "Complex modulus", back: "|a+bi| = √(a²+b²)" },
      { id: "maac-11", front: "Pythagorean identity", back: "sin²x + cos²x = 1" },
      { id: "maac-12", front: "Double angle (sin)", back: "sin 2x = 2 sin x cos x" },
      { id: "maac-13", front: "Dot product", back: "a·b = |a||b|cos θ" },
      { id: "maac-14", front: "Chain rule", back: "d/dx f(g(x)) = f′(g(x))·g′(x)" },
      { id: "maac-15", front: "Product rule", back: "(uv)′ = u′v + uv′" },
      { id: "maac-16", front: "Power rule (diff)", back: "d/dx xⁿ = nxⁿ⁻¹" },
      { id: "maac-17", front: "∫xⁿ dx", back: "xⁿ⁺¹/(n+1) + C" },
      { id: "maac-18", front: "Conditional probability", back: "P(A|B) = P(A∩B)/P(B)" },
      { id: "maac-19", front: "Expected value", back: "E(X) = Σx·P(X=x)" },
      { id: "maac-20", front: "L'Hôpital's rule", back: "For 0/0 or ∞/∞: lim f/g = lim f′/g′" },
    ],
  },
  {
    id: "deck-english-langlit",
    subjectSlug: "english-langlit",
    title: "English L&L analysis toolkit",
    cards: [
      { id: "elc-1", front: "Global issue (IO)", back: "Transnational in scale, locally felt, evidenced in both extracts" },
      { id: "elc-2", front: "The 7 concepts", back: "Identity, culture, creativity, communication, perspective, transformation, representation" },
      { id: "elc-3", front: "Areas of exploration", back: "Readers/writers/texts; time & space; intertextuality" },
      { id: "elc-4", front: "Juxtaposition", back: "Placing contrasting elements together to sharpen meaning" },
      { id: "elc-5", front: "Anaphora", back: "Repetition at the start of successive clauses for emphasis" },
      { id: "elc-6", front: "Tone", back: "The writer's attitude conveyed through style and word choice" },
      { id: "elc-7", front: "Connotation vs denotation", back: "Implied associations vs literal meaning" },
      { id: "elc-8", front: "Intertextuality", back: "How texts reference, echo or transform other texts" },
      { id: "elc-9", front: "Allusion", back: "An indirect reference relying on shared cultural knowledge" },
      { id: "elc-10", front: "Parody", back: "Imitating a text's style for comic or critical effect" },
      { id: "elc-11", front: "Direct address", back: "Speaking straight to the reader ('you') to involve them" },
      { id: "elc-12", front: "Triadic structure", back: "Groups of three for rhythm, completeness, memorability" },
      { id: "elc-13", front: "Register", back: "Level of formality suited to audience and context" },
      { id: "elc-14", front: "Paper 1", back: "Guided textual analysis of unseen non-literary text(s)" },
      { id: "elc-15", front: "Paper 2", back: "Comparative essay on two studied literary works" },
      { id: "elc-16", front: "HL essay", back: "1200–1500 word essay on a studied text via a line of inquiry" },
      { id: "elc-17", front: "Individual oral", back: "10 min analysis of two extracts linked by a global issue" },
      { id: "elc-18", front: "Ethos / pathos / logos", back: "Appeals to credibility, emotion, and logic" },
      { id: "elc-19", front: "Structural features", back: "Layout, headings, typography, images — design choices that carry meaning" },
      { id: "elc-20", front: "Line of inquiry", back: "A focused, arguable question guiding the HL essay" },
    ],
  },
  {
    id: "deck-business-management",
    subjectSlug: "business-management",
    title: "Business Management key formulas & terms",
    cards: [
      { id: "bmc-1", front: "SMART objectives", back: "Specific, Measurable, Achievable, Relevant, Time-bound" },
      { id: "bmc-2", front: "Stakeholder", back: "Any person/group with an interest in the business" },
      { id: "bmc-3", front: "Limited liability", back: "Owners risk only invested capital" },
      { id: "bmc-4", front: "Economies of scale", back: "Falling average costs as output rises" },
      { id: "bmc-5", front: "Span of control", back: "Subordinates per manager; wide = flat, narrow = tall" },
      { id: "bmc-6", front: "Maslow's hierarchy", back: "Physiological → safety → social → esteem → self-actualisation" },
      { id: "bmc-7", front: "Herzberg hygiene factors", back: "Prevent dissatisfaction but don't motivate (pay, conditions)" },
      { id: "bmc-8", front: "Gross profit margin", back: "(Revenue − COGS) / revenue × 100" },
      { id: "bmc-9", front: "Current ratio", back: "Current assets / current liabilities" },
      { id: "bmc-10", front: "Gearing", back: "Loan capital / total capital employed × 100" },
      { id: "bmc-11", front: "Payback period", back: "Initial cost / annual cash flow" },
      { id: "bmc-12", front: "NPV", back: "Sum of discounted cash flows − cost; >0 = invest" },
      { id: "bmc-13", front: "Break-even output", back: "Fixed costs / (price − variable cost)" },
      { id: "bmc-14", front: "Contribution", back: "Price − variable cost per unit" },
      { id: "bmc-15", front: "Margin of safety", back: "Actual output − break-even output" },
      { id: "bmc-16", front: "7 Ps", back: "Product, price, place, promotion, people, process, physical evidence" },
      { id: "bmc-17", front: "SWOT", back: "Strengths, weaknesses (internal); opportunities, threats (external)" },
      { id: "bmc-18", front: "JIT", back: "Just-in-time: stock arrives only as needed" },
      { id: "bmc-19", front: "Kaizen", back: "Continuous improvement in small steps, involving all staff" },
      { id: "bmc-20", front: "Variance", back: "Budgeted − actual figure; favourable or adverse" },
    ],
  },
];
