import type { Deck } from "./types";

export const decks: Deck[] = [
  {
    id: "deck-math-aa",
    subjectSlug: "math-aa",
    title: "Math AA essentials",
    cards: [
      { id: "maac-1", front: "Arithmetic sequence nth term", back: "uₙ = u₁ + (n − 1)d" },
      { id: "maac-2", front: "Arithmetic series sum", back: "Sₙ = n/2 (2u₁ + (n−1)d) = n/2 (u₁ + uₙ)" },
      { id: "maac-3", front: "Geometric sequence nth term", back: "uₙ = u₁ · rⁿ⁻¹" },
      { id: "maac-4", front: "Geometric series sum (finite)", back: "Sₙ = u₁(rⁿ − 1)/(r − 1), r ≠ 1" },
      { id: "maac-5", front: "Geometric series sum (infinite)", back: "S∞ = u₁/(1 − r), |r| < 1" },
      { id: "maac-6", front: "Quadratic formula", back: "x = (−b ± √(b² − 4ac)) / 2a" },
      { id: "maac-7", front: "Discriminant", back: "Δ = b² − 4ac; >0 two roots, =0 one root, <0 no real roots" },
      { id: "maac-8", front: "Vertex x-coordinate", back: "x = −b / 2a" },
      { id: "maac-9", front: "Power rule", back: "d/dx xⁿ = nxⁿ⁻¹" },
      { id: "maac-10", front: "Chain rule", back: "d/dx f(g(x)) = f′(g(x)) · g′(x)" },
      { id: "maac-11", front: "Product rule", back: "(uv)′ = u′v + uv′" },
      { id: "maac-12", front: "d/dx eˣ", back: "eˣ" },
      { id: "maac-13", front: "d/dx ln x", back: "1/x (x > 0)" },
      { id: "maac-14", front: "∫xⁿ dx", back: "xⁿ⁺¹/(n+1) + C, n ≠ −1" },
      { id: "maac-15", front: "Composite function", back: "f(g(x)) — apply g first, then f" },
    ],
  },
  {
    id: "deck-physics",
    subjectSlug: "physics",
    title: "Physics essentials",
    cards: [
      { id: "phyc-1", front: "v = u + at", back: "Final velocity under constant acceleration" },
      { id: "phyc-2", front: "s = ut + ½at²", back: "Displacement under constant acceleration" },
      { id: "phyc-3", front: "v² = u² + 2as", back: "Velocity–displacement relation (no time)" },
      { id: "phyc-4", front: "Newton's 2nd law", back: "F = ma — resultant force" },
      { id: "phyc-5", front: "Weight", back: "W = mg (g ≈ 9.81 N/kg)" },
      { id: "phyc-6", front: "Kinetic energy", back: "Ek = ½mv²" },
      { id: "phyc-7", front: "Gravitational PE", back: "Ep = mgh" },
      { id: "phyc-8", front: "Momentum", back: "p = mv — conserved in closed systems" },
      { id: "phyc-9", front: "Work done", back: "W = Fd cos θ" },
      { id: "phyc-10", front: "Power", back: "P = E/t = W/t (watts)" },
      { id: "phyc-11", front: "Wave equation", back: "v = fλ" },
      { id: "phyc-12", front: "Period", back: "T = 1/f (seconds)" },
      { id: "phyc-13", front: "Pendulum period", back: "T = 2π√(l/g)" },
      { id: "phyc-14", front: "SHM acceleration", back: "a = −ω²x, towards equilibrium" },
      { id: "phyc-15", front: "Speed of light", back: "c ≈ 3.0 × 10⁸ m/s" },
    ],
  },
  {
    id: "deck-chemistry",
    subjectSlug: "chemistry",
    title: "Chemistry essentials",
    cards: [
      { id: "chc-1", front: "Moles from mass", back: "n = m/M" },
      { id: "chc-2", front: "Avogadro's constant", back: "NA = 6.022 × 10²³ mol⁻¹" },
      { id: "chc-3", front: "Particles", back: "N = n × NA" },
      { id: "chc-4", front: "Concentration", back: "c = n/V (mol·dm⁻³)" },
      { id: "chc-5", front: "Dilution", back: "c₁V₁ = c₂V₂" },
      { id: "chc-6", front: "Ideal gas law", back: "PV = nRT (R = 8.31 J·K⁻¹·mol⁻¹)" },
      { id: "chc-7", front: "Molar volume at STP", back: "22.7 dm³/mol (100 kPa, 0 °C)" },
      { id: "chc-8", front: "Limiting reactant", back: "Runs out first; caps the product formed" },
      { id: "chc-9", front: "Ionic bond", back: "Electron transfer; metal + non-metal; ions attract" },
      { id: "chc-10", front: "Covalent bond", back: "Shared electron pair between non-metals" },
      { id: "chc-11", front: "Metallic bond", back: "Cations in a sea of delocalised electrons" },
      { id: "chc-12", front: "CH₄ shape", back: "Tetrahedral, 109.5°" },
      { id: "chc-13", front: "NH₃ shape", back: "Trigonal pyramidal, ~107°" },
      { id: "chc-14", front: "H₂O shape", back: "Bent, ~104.5° (2 lone pairs)" },
      { id: "chc-15", front: "Hydrogen bonding", back: "H bonded to N, O or F — strongest IMF" },
    ],
  },
  {
    id: "deck-economics",
    subjectSlug: "economics",
    title: "Economics essentials",
    cards: [
      { id: "ecc-1", front: "Law of demand", back: "Price ↑ → quantity demanded ↓ (ceteris paribus)" },
      { id: "ecc-2", front: "Law of supply", back: "Price ↑ → quantity supplied ↑ (ceteris paribus)" },
      { id: "ecc-3", front: "Market equilibrium", back: "Qd = Qs; no price-change pressure" },
      { id: "ecc-4", front: "Surplus", back: "Price above equilibrium; Qs > Qd" },
      { id: "ecc-5", front: "Shortage", back: "Price below equilibrium; Qd > Qs" },
      { id: "ecc-6", front: "PED", back: "%ΔQd / %ΔP; elastic if |PED| > 1" },
      { id: "ecc-7", front: "Substitutes", back: "Price of A ↑ → demand for B ↑ (e.g. coffee/tea)" },
      { id: "ecc-8", front: "Normal good", back: "Income ↑ → demand ↑" },
      { id: "ecc-9", front: "Inferior good", back: "Income ↑ → demand ↓" },
      { id: "ecc-10", front: "GDP", back: "Value of all final goods & services produced per period" },
      { id: "ecc-11", front: "Real GDP", back: "GDP at constant prices — adjusted for inflation" },
      { id: "ecc-12", front: "Inflation", back: "Sustained rise in general price level; measured by CPI" },
      { id: "ecc-13", front: "Unemployment rate", back: "Unemployed / labour force × 100" },
      { id: "ecc-14", front: "Fiscal policy", back: "Government spending & taxation (G and T)" },
      { id: "ecc-15", front: "Monetary policy", back: "Interest rates & money supply (central bank)" },
    ],
  },
];
